packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - svelte-preprocess
  - workerd
