# @format

packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"
onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - "@parcel/watcher"
  - sharp
  - svelte-preprocess
  - workerd
  - better-sqlite3
