ALTER TABLE `result_snapshots` ADD `total_sessions` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `neither_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `avg_response_time_ms` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `flac_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `flac_comparisons` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `opus_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `opus_comparisons` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `aac_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `aac_comparisons` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `mp3_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `mp3_comparisons` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `bitrate_lossless_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `bitrate_high_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `bitrate_mid_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `bitrate_low_win_rate` real;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `lossless_vs_lossy_lossless_wins` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `lossless_vs_lossy_total` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `opus_vs_mp3_opus_wins` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `opus_vs_mp3_total` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `aac_vs_mp3_aac_wins` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `aac_vs_mp3_total` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `device_headphones_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `device_speakers_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `tier_budget_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `tier_mid_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `tier_premium_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `tier_flagship_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `comparison_same_gapless_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `comparison_same_gap_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `comparison_different_gapless_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `comparison_different_gap_count` integer;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `codec_matchup_matrix` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `bitrate_gap_confidence` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `codec_equivalence_ratios` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `flac_vs_lossy_win_rates` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `codec_pq_scores` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `transparency_thresholds` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `diminishing_returns_points` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `codec_pq_scores_by_genre` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `cross_genre_quality_tradeoff` text;--> statement-breakpoint
ALTER TABLE `result_snapshots` ADD `quality_vs_content_by_gap` text;--> statement-breakpoint
ALTER TABLE `source_files` ADD `genre_secondary` text;