# @format

apiVersion: v1
kind: Service
metadata:
  name: euterpe-canary
  labels:
    app: euterpe-canary
spec:
  type: ClusterIP
  selector:
    app: euterpe-canary
  ports:
    - name: http
      port: 80
      targetPort: 3000
